services:
  backend:
    environment:
      QUESTDB_HOST: questdb
    depends_on:
      qdrant:
        condition: service_started
      questdb:
        condition: service_started

  timescaledb:
    image: timescale/timescaledb:2.27.1-pg18
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U logto -d logto"]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - "./timescaledb:/var/lib/postgresql/data"

  timescaledb-init:
    image: postgres:15-alpine
    restart: "no"
    depends_on:
      timescaledb:
        condition: service_started
    volumes:
      - ./sql/init.sql:/init/init.sql:ro
      - ./sql/init.sh:/init/init_tdb.sh:ro
    env_file:
      - .env
    working_dir: /init
    entrypoint: ["sh", "/init/init.sh"]


  questdb:
    image: questdb/questdb:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:9000:9000"
    environment:
      - QDB_HTTP_BIND_TO=0.0.0.0:9000
      - QDB_PG_ENABLED=true
      - QDB_HTTP_USER=${QUESTDB_HTTP_USER}
      - QDB_HTTP_PASSWORD=${QUESTDB_HTTP_PASSWORD}
      - QDB_PG_USER=${QUESTDB_USER}
      - QDB_PG_PASSWORD=${QUESTDB_PASSWORD}
    volumes:
      - ./questdb:/root/.questdb:rw
    env_file:
      - .env

  questdb-init:
    image: postgres:15-alpine
    restart: "no"
    depends_on:
      questdb:
        condition: service_started
    volumes:
      - ./sql/init.sql:/init/init.sql:ro
      - ./sql/init.sh:/init/init.sh:ro
    env_file:
      - .env
    working_dir: /init
    entrypoint: ["sh", "/init/init.sh"]

  logto:
    image: ghcr.io/logto-io/logto:1.36.0
    depends_on:
      logto-postgres:
        condition: service_healthy
    entrypoint: ["sh", "-c", "npm run cli db seed -- --swe && npm start"]
    ports:
      - "3011:3001"
      - "3002:3002"
    environment:
      TRUST_PROXY_HEADER: 1
      DB_URL: postgres://logto:${LOGTO_POSTGRES_PASSWORD}@logto-postgres:5432/logto
      ENDPOINT: ${LOGTO_ENDPOINT}
      ADMIN_ENDPOINT: ${LOGTO_ADMIN_ENDPOINT}
    volumes:
      - logto-connectors:/etc/logto/packages/core/connectors
    restart: unless-stopped

  logto-postgres:
    image: postgres:18-alpine
    user: postgres
    environment:
      POSTGRES_USER: logto
      POSTGRES_DB: logto
      POSTGRES_PASSWORD: ${LOGTO_POSTGRES_PASSWORD}
    volumes:
      - logto-postgres-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U logto -d logto"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  logto-connectors:
  logto-postgres-data:
