version: "3.9"
services:
  app:
    build: .
    image: mi-streamlit:latest
    container_name: mi-streamlit
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./faiss_index:/app/faiss_index:rw
      - ./secrets/client_secret.json:/app/client_secret.json:ro
      - ./secrets/client_secret_website.json:/app/client_secret_website.json:ro
      - ./img:/app/img:rw
      - ./src:/app/src:rw
      - ./app.py:/app/app.py:rw
    user: "${UID}:${GID}"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.default.disable_ipv6=1
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://127.0.0.1:8501/_stcore/health || exit 1" ]
      interval: 15s
      timeout: 5s
      retries: 5

  questdb:
    image: questdb/questdb:latest
    container_name: questdb
    restart: unless-stopped
    # Ports:
    # 9000 - QuestDB web console / REST API (HTTP)
    # 8812 - Postgres wire protocol (useable with psql / Postgres clients / SQL interfaces)
    # 9009 - InfluxDB Line Protocol (ILP)
    ports:
      - "9000:9000"
      - "8812:8812"
      - "9009:9009"
    volumes:
      - ./questdb:/root/.questdb:rw
    environment:
      - TZ=Europe/Madrid
      
  questdb-init:
    image: postgres:15-alpine
    container_name: questdb-init
    restart: "no"
    depends_on:
      - questdb
    volumes:
      - ./sql/init.sql:/init/init.sql:ro
      - ./sql/init.sh:/init/init.sh:ro
    environment:
      QUESTDB_HOST: questdb
      QUESTDB_PORT: "8812"   # PGWire port
      QUESTDB_USER: admin
      QUESTDB_PASSWORD: quest
      QUESTDB_DB: qdb
    working_dir: /init
    entrypoint: ["sh", "/init/init.sh"]