export { closePool, executeQuery } from "./connection";
export {
  countMetrics,
  getActivityByDay,
  getDetailedStatusCodes,
  getErrorRate,
  getErrorRateByEndpoint,
  getHourlyActivityPattern,
  getLatencyByEndpoint,
  getLatencyDistribution,
  getMetricsByTag,
  getRequestsByDay,
  getRequestStats,
  getTotalActivityEvents,
  getUniqueUsers,
  getUserRoleDistribution,
  meanMetric,
  meanSessionLength,
  topKSearchTerms,
  topKTopics,
  type ActivityByDay,
  type EndpointErrorRate,
  type EndpointLatency,
  type HourlyActivity,
  type LatencyDistribution,
  type MetricsByTag,
  type MetricsQueryParams,
  type RequestsByDay,
  type RequestStats,
  type SearchTerm,
  type StatusCodeDetail,
  type TopicCount,
} from "./metrics-queries";
