export { closePool, executeQuery } from "./connection";
export {
  countMetrics,
  getActivityByDay,
  getHourlyActivityPattern,
  getMetricsByTag,
  getTotalActivityEvents,
  getUniqueUsers,
  getUserRoleDistribution,
  meanMetric,
  meanSessionLength,
  topKSearchTerms,
  topKTopics,
  type ActivityByDay,
  type HourlyActivity,
  type MetricsByTag,
  type MetricsQueryParams,
  type SearchTerm,
  type TopicCount,
} from "./metrics-queries";
